use astra_core::hashing::hash_to_hex;

use astra_research::phantom_runner::PhantomRunner;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[test]
fn test_golden_hash_regression() {
    let base_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let golden_path = base_dir.join("../../research/golden_hashes.json");

    // Attempt to load the golden hashes, if they don't exist, we fail.
    let golden_content =
        fs::read_to_string(&golden_path).expect("Could not read golden_hashes.json");
    let golden_hashes: BTreeMap<String, String> =
        serde_json::from_str(&golden_content).expect("Invalid JSON in golden_hashes.json");

    // We expect the datasets to be in the `research` directory generated by `astra-research`
    // but tests might run in parallel or before the datasets exist.
    // Let's generate them right now dynamically or read them if they exist.
    let datasets = vec![
        (
            "flash_crash_2010",
            astra_research::flash_crash_dataset::build_flash_crash_events(),
        ),
        (
            "lehman_2008",
            astra_research::lehman_2008_dataset::build_lehman_collapse_events(),
        ),
        (
            "covid_2020",
            astra_research::covid_2020_dataset::build_covid_crash_events(),
        ),
    ];

    for (id, events) in datasets {
        let expected_hash = golden_hashes
            .get(id)
            .unwrap_or_else(|| panic!("Missing hash for {}", id));

        let dataset = astra_research::dataset_format::CrisisDataset {
            header: astra_research::dataset_format::DatasetHeader {
                format_version: 1,
                crisis_name: id.to_string(),
                date_range: "".to_string(),
                event_count: events.len() as u64,
            },
            events,
        };

        let mut runner = PhantomRunner::new();
        runner.run(&dataset, 100);
        let actual_hash = hash_to_hex(&runner.final_hash());

        assert_eq!(
            &actual_hash, expected_hash,
            "Golden hash regression failed for {}. Expected: {}, Actual: {}",
            id, expected_hash, actual_hash
        );
    }
}
